name: All Tests

on: pull_request

jobs:
  lint:
    name: Lint and typecheck Python code
    runs-on:
      - runs-on=${{ github.run_id }}
      - job=lint
      - extras=s3-cache
    steps:
      - uses: actions/checkout@v5
      - uses: citizensadvice/python-uv-setup-action@v1
      - uses: extractions/setup-just@v3
      - run: just lint

  test:
    name: Run Python tests
    runs-on:
      - runs-on=${{ github.run_id }}
      - job=test
      - extras=s3-cache
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: citizensadvice/python-uv-setup-action@v1
      - uses: extractions/setup-just@v3
      - run: just all-tests
